source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'Singularity-iOS'
end
target 'Unity-iPhone' do
  pod 'Singularity-iOS'
end
use_frameworks! :linkage => :static
